project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('todo.urls')),
    path('superuser/', admin.site.urls),
]

project/todo/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = "todo"

urlpatterns = [
    path("", views.index, name="index"),
    path("check/<int:pk>/", views.todo_check, name="todo_done"),
    path("delete/<int:pk>/", views.todo_delete, name="todo_delete"),
    path("api/todos/", views.todo_list, name="todo_list"),
    path("api/todos/<int:pk>/", views.todo_detail, name="todo_detail"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

project/todo/models.py
from django.db import models


class Todo(models.Model):
    todo_text = models.CharField(max_length=100, blank=False)
    todo_done = models.BooleanField(default=False)

    def __str__(self):
        return self.todo_text

project/todo/forms.py
from django import forms
from django.forms import ModelForm
from todo.models import Todo


class AddTodoForm(forms.Form):
    new_todo = forms.CharField(
        max_length=100,
        required=True,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "things to do...",
            "autofocus": "",
            "autocomplete": "off",
        }))

    def clean_new_todo(self):
        new_todo = self.cleaned_data["new_todo"]

        return new_todo


class EditTodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ["todo_text"]

    def __init__(self, *args, **kwargs):
        super(EditTodoForm, self).__init__(*args, **kwargs)
        self.fields["todo_text"].widget = forms.TextInput(attrs={
            "value": self.fields["todo_text"],
            "required": "",
        })

project/todo/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.urls import reverse

from .models import Todo
from .forms import AddTodoForm, EditTodoForm
from .serializers import TodoSerializer


# display all todos
def index(request):
    if request.method == "POST":
        form = AddTodoForm(request.POST)
        if form.is_valid():
            new_todo = Todo()
            new_todo.todo_text = form.cleaned_data["new_todo"]
            new_todo.save()
            return HttpResponseRedirect(reverse("todo:index"))
    elif request.method == "GET":
        form = AddTodoForm()

    todos = Todo.objects.all().order_by("-pk")
    todo_forms = [EditTodoForm(instance=todo) for todo in todos]
    todo_list = list(zip(todos, todo_forms))
    context = {
        "form": form,
        "todo_list": todo_list,
    }
    return render(request, "todo/index.html", context)


# to check a todo
def todo_check(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    todo.todo_done = not todo.todo_done
    todo.save()
    return HttpResponseRedirect(reverse("todo:index"))


# to delete a todo
def todo_delete(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    todo.delete()
    return HttpResponseRedirect(reverse("todo:index"))


@csrf_exempt
@api_view(["GET", "POST"])
def todo_list(request, format=None):
    if request.method == "GET":
        todos = Todo.objects.all()
        serializer = TodoSerializer(todos, many=True)
        return Response(serializer.data)
    elif request.method == "POST":
        serializer = TodoSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,
                            status=status.HTTP_201_CREATED)
        return Response(serializer.errors,
                        status=status.HTTP_400_BAD_REQUEST)


@csrf_exempt
@api_view(["GET", "PUT", "DELETE"])
def todo_detail(request, pk, format=None):
    todo = get_object_or_404(Todo, pk=pk)
    if request.method == "GET":
        serializer = TodoSerializer(todo)
        return Response(serializer.data)
    elif request.method == "PUT":
        serializer = TodoSerializer(todo, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors,
                        status=status.HTTP_400_BAD_REQUEST)
    elif request.method == "DELETE":
        todo.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

project/todo/templates/todo/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Todo App</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Monoton&display=swap" rel="stylesheet">  
    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/todo.css' %}">
  </head>
  <body>
    <header>
        <h1 class="title">TODO</h1>
    </header>
    <main>
        {% block content %}
        {% endblock %} 
    </main>
  </body>
</html>

project/todo/templates/todo/index.html
{% extends "todo/base.html" %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        {{ field }}
        {% endfor %}
        <button type="submit">
            <div class="plus"></div>
        </button>
    </form>
    <article class="todo-list">
        {% for todo, todo_form in todo_list %}
            <section class="todo">
                <a href="{% url 'todo:todo_done' todo.pk %}" class="todo__check {% if todo.todo_done %}todo__check--checked{% endif %}"></a>
                <form action="" method="post" class="todo__text {% if todo.todo_done %}todo__text--checked{% endif %}">
                  {% csrf_token %}
                  {% for field in todo_form.visible_fields %}
                  {{ field }}
                  {% endfor %}
                </form>
                <a href="{% url 'todo:todo_delete' todo.pk %}" class="todo__delete plus"></a>
            </section>
        {% endfor %}
    </article>

{% endblock %}        